#pragma once

struct Config {
	BOOLEAN Process;
};

#define PRIORITY_COLLECTOR_DEVICE 0x8000
#define DRIVER_TAG 'VXER'

#define IOCTL_PRIORITY_COLLECTOR_GET_EVIDENCE CTL_CODE(PRIORITY_COLLECTOR_DEVICE, \
	0x800, METHOD_NEITHER, FILE_ANY_ACCESS)