#pragma once

struct Config {
	PCHAR Process;
};

#define EVIDENCE_COLLECTOR_DEVICE 0x8000
#define DRIVER_TAG 'VXER'

#define IOCTL_EVIDENCE_COLLECTOR_GET_PROCESSLIST CTL_CODE(EVIDENCE_COLLECTOR_DEVICE, \
	0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

const size_t LenProcessList = 0x2000;